# Generated by Django 4.2.3 on 2025-09-15 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_complaint_complaintcategory_zone_ward_supervisor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintsubcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='ward',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='zone',
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.DeleteModel(
            name='ComplaintCategory',
        ),
        migrations.DeleteModel(
            name='ComplaintSubCategory',
        ),
        migrations.DeleteModel(
            name='Supervisor',
        ),
        migrations.DeleteModel(
            name='Ward',
        ),
        migrations.DeleteModel(
            name='Zone',
        ),
    ]
