# Generated by Django 4.2.3 on 2025-09-15 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usertoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserToken',
        ),
    ]
