# Generated by Django 5.2.3 on 2025-07-02 03:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('code_type', models.CharField(max_length=100)),
                ('code_path', models.CharField(blank=True, max_length=500, null=True)),
                ('isdeleted', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('reserver_1', models.IntegerField(default=0)),
                ('reserver_2', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, default=0, null=True)),
                ('user_name', models.CharField(max_length=100)),
                ('user_type', models.IntegerField(blank=True, choices=[(1, 'ADMIN'), (2, 'USER'), (3, 'STORE_MANAGER'), (4, 'PRODUCTION_MANAGER'), (5, 'QUALITY_CONTROL'), (6, 'PURCHASE_MANAGER')], null=True)),
                ('business_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('contact_number', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=128)),
                ('address', models.TextField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_datetime', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
            options={
                'db_table': 'ms_user_profiles',
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.userprofile')),
            ],
            options={
                'db_table': 'ms_user_token',
            },
        ),
    ]
