# Generated by Django 4.2.3 on 2025-09-13 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_userprofile_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropdownValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('zone', 'Zone'), ('ward', 'Ward'), ('complaint_category', 'Complaint Category')], max_length=50)),
                ('value', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ms_dropdown_values',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint_category', models.CharField(max_length=50)),
                ('complaint_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('zone', models.CharField(max_length=100)),
                ('ward', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('landmark', models.CharField(blank=True, max_length=200)),
                ('complaint_location', models.CharField(max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('complaint_image', models.ImageField(blank=True, null=True, upload_to='complaints/')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=200)),
                ('address2', models.CharField(blank=True, max_length=200)),
                ('area', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('share_publicly', models.BooleanField(default=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='base_app.userprofile')),
            ],
            options={
                'db_table': 'ms_complaints',
            },
        ),
    ]
