# Generated by Django 4.2.3 on 2025-09-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0005_alter_userprofile_user_type_complaintsubcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint_subcategory',
            field=models.CharField(default='General', max_length=50),
            preserve_default=False,
        ),
    ]
