# Generated by Django 4.2.3 on 2025-09-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0006_complaint_complaint_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(default='CITIZEN', max_length=20),
        ),
    ]
